# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\006./node',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnode_grpc.proto\"\x18\n\tOneString\x12\x0b\n\x03Msg\x18\x01 \x01(\t\"\"\n\x06KVPair\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\x0b\n\x03Val\x18\x02 \x01(\t\"Q\n\nInitConfig\x12\x0f\n\x07RaftDir\x18\x01 \x01(\t\x12\x10\n\x08RaftAddr\x18\x02 \x01(\t\x12\x10\n\x08StoreDir\x18\x03 \x01(\t\x12\x0e\n\x06NodeID\x18\x04 \x01(\t\"*\n\nJoinConfig\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0c\n\x04\x41\x64\x64r\x18\x02 \x01(\t2\xd2\x01\n\x04Node\x12!\n\x04Init\x12\x0b.InitConfig\x1a\n.OneString\"\x00\x12!\n\x04Join\x12\x0b.JoinConfig\x1a\n.OneString\"\x00\x12\x1f\n\x03Get\x12\n.OneString\x1a\n.OneString\"\x00\x12\x1c\n\x03Put\x12\x07.KVPair\x1a\n.OneString\"\x00\x12\"\n\x06\x44\x65lete\x12\n.OneString\x1a\n.OneString\"\x00\x12!\n\x05\x43lose\x12\n.OneString\x1a\n.OneString\"\x00\x42\x08Z\x06./nodeb\x06proto3'
)




_ONESTRING = _descriptor.Descriptor(
  name='OneString',
  full_name='OneString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Msg', full_name='OneString.Msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=43,
)


_KVPAIR = _descriptor.Descriptor(
  name='KVPair',
  full_name='KVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='KVPair.Key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Val', full_name='KVPair.Val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=79,
)


_INITCONFIG = _descriptor.Descriptor(
  name='InitConfig',
  full_name='InitConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RaftDir', full_name='InitConfig.RaftDir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RaftAddr', full_name='InitConfig.RaftAddr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StoreDir', full_name='InitConfig.StoreDir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NodeID', full_name='InitConfig.NodeID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=162,
)


_JOINCONFIG = _descriptor.Descriptor(
  name='JoinConfig',
  full_name='JoinConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NodeID', full_name='JoinConfig.NodeID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Addr', full_name='JoinConfig.Addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['OneString'] = _ONESTRING
DESCRIPTOR.message_types_by_name['KVPair'] = _KVPAIR
DESCRIPTOR.message_types_by_name['InitConfig'] = _INITCONFIG
DESCRIPTOR.message_types_by_name['JoinConfig'] = _JOINCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OneString = _reflection.GeneratedProtocolMessageType('OneString', (_message.Message,), {
  'DESCRIPTOR' : _ONESTRING,
  '__module__' : 'node_grpc_pb2'
  # @@protoc_insertion_point(class_scope:OneString)
  })
_sym_db.RegisterMessage(OneString)

KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), {
  'DESCRIPTOR' : _KVPAIR,
  '__module__' : 'node_grpc_pb2'
  # @@protoc_insertion_point(class_scope:KVPair)
  })
_sym_db.RegisterMessage(KVPair)

InitConfig = _reflection.GeneratedProtocolMessageType('InitConfig', (_message.Message,), {
  'DESCRIPTOR' : _INITCONFIG,
  '__module__' : 'node_grpc_pb2'
  # @@protoc_insertion_point(class_scope:InitConfig)
  })
_sym_db.RegisterMessage(InitConfig)

JoinConfig = _reflection.GeneratedProtocolMessageType('JoinConfig', (_message.Message,), {
  'DESCRIPTOR' : _JOINCONFIG,
  '__module__' : 'node_grpc_pb2'
  # @@protoc_insertion_point(class_scope:JoinConfig)
  })
_sym_db.RegisterMessage(JoinConfig)


DESCRIPTOR._options = None

_NODE = _descriptor.ServiceDescriptor(
  name='Node',
  full_name='Node',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=209,
  serialized_end=419,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='Node.Init',
    index=0,
    containing_service=None,
    input_type=_INITCONFIG,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Join',
    full_name='Node.Join',
    index=1,
    containing_service=None,
    input_type=_JOINCONFIG,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='Node.Get',
    index=2,
    containing_service=None,
    input_type=_ONESTRING,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='Node.Put',
    index=3,
    containing_service=None,
    input_type=_KVPAIR,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='Node.Delete',
    index=4,
    containing_service=None,
    input_type=_ONESTRING,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='Node.Close',
    index=5,
    containing_service=None,
    input_type=_ONESTRING,
    output_type=_ONESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODE)

DESCRIPTOR.services_by_name['Node'] = _NODE

# @@protoc_insertion_point(module_scope)
