// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: node_grpc.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *OneString) Reset() {
	*x = OneString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneString) ProtoMessage() {}

func (x *OneString) ProtoReflect() protoreflect.Message {
	mi := &file_node_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneString.ProtoReflect.Descriptor instead.
func (*OneString) Descriptor() ([]byte, []int) {
	return file_node_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *OneString) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type KVPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_node_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_node_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *KVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPair) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type InitConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RaftDir  string `protobuf:"bytes,1,opt,name=RaftDir,proto3" json:"RaftDir,omitempty"`
	RaftAddr string `protobuf:"bytes,2,opt,name=RaftAddr,proto3" json:"RaftAddr,omitempty"`
	StoreDir string `protobuf:"bytes,3,opt,name=StoreDir,proto3" json:"StoreDir,omitempty"`
	NodeID   string `protobuf:"bytes,4,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
}

func (x *InitConfig) Reset() {
	*x = InitConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConfig) ProtoMessage() {}

func (x *InitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConfig.ProtoReflect.Descriptor instead.
func (*InitConfig) Descriptor() ([]byte, []int) {
	return file_node_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *InitConfig) GetRaftDir() string {
	if x != nil {
		return x.RaftDir
	}
	return ""
}

func (x *InitConfig) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *InitConfig) GetStoreDir() string {
	if x != nil {
		return x.StoreDir
	}
	return ""
}

func (x *InitConfig) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type JoinConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID string `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Addr   string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *JoinConfig) Reset() {
	*x = JoinConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConfig) ProtoMessage() {}

func (x *JoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConfig.ProtoReflect.Descriptor instead.
func (*JoinConfig) Descriptor() ([]byte, []int) {
	return file_node_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *JoinConfig) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *JoinConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_node_grpc_proto protoreflect.FileDescriptor

var file_node_grpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1d, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67,
	0x22, 0x2c, 0x0a, 0x06, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x76,
	0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x52, 0x61, 0x66, 0x74, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52,
	0x61, 0x66, 0x74, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x61, 0x66, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x61, 0x66, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72,
	0x32, 0xd2, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x49, 0x6e, 0x69,
	0x74, 0x12, 0x0b, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x0a,
	0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x04,
	0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12,
	0x1f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x1a, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00,
	0x12, 0x1c, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x07, 0x2e, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72,
	0x1a, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x22,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x00, 0x12, 0x21, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x0a, 0x2e, 0x4f, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x0a, 0x2e, 0x4f, 0x6e, 0x65, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_grpc_proto_rawDescOnce sync.Once
	file_node_grpc_proto_rawDescData = file_node_grpc_proto_rawDesc
)

func file_node_grpc_proto_rawDescGZIP() []byte {
	file_node_grpc_proto_rawDescOnce.Do(func() {
		file_node_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_grpc_proto_rawDescData)
	})
	return file_node_grpc_proto_rawDescData
}

var file_node_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_node_grpc_proto_goTypes = []interface{}{
	(*OneString)(nil),  // 0: OneString
	(*KVPair)(nil),     // 1: KVPair
	(*InitConfig)(nil), // 2: InitConfig
	(*JoinConfig)(nil), // 3: JoinConfig
}
var file_node_grpc_proto_depIdxs = []int32{
	2, // 0: Node.Init:input_type -> InitConfig
	3, // 1: Node.Join:input_type -> JoinConfig
	0, // 2: Node.Get:input_type -> OneString
	1, // 3: Node.Put:input_type -> KVPair
	0, // 4: Node.Delete:input_type -> OneString
	0, // 5: Node.Close:input_type -> OneString
	0, // 6: Node.Init:output_type -> OneString
	0, // 7: Node.Join:output_type -> OneString
	0, // 8: Node.Get:output_type -> OneString
	0, // 9: Node.Put:output_type -> OneString
	0, // 10: Node.Delete:output_type -> OneString
	0, // 11: Node.Close:output_type -> OneString
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_grpc_proto_init() }
func file_node_grpc_proto_init() {
	if File_node_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_grpc_proto_goTypes,
		DependencyIndexes: file_node_grpc_proto_depIdxs,
		MessageInfos:      file_node_grpc_proto_msgTypes,
	}.Build()
	File_node_grpc_proto = out.File
	file_node_grpc_proto_rawDesc = nil
	file_node_grpc_proto_goTypes = nil
	file_node_grpc_proto_depIdxs = nil
}
