// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplicaSetClient is the client API for ReplicaSet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicaSetClient interface {
	Init(ctx context.Context, in *InitConfig, opts ...grpc.CallOption) (*OneString, error)
	Join(ctx context.Context, in *JoinConfig, opts ...grpc.CallOption) (*OneString, error)
	RemoveNode(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error)
	Get(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error)
	Put(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*OneString, error)
	Delete(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error)
}

type replicaSetClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicaSetClient(cc grpc.ClientConnInterface) ReplicaSetClient {
	return &replicaSetClient{cc}
}

func (c *replicaSetClient) Init(ctx context.Context, in *InitConfig, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaSetClient) Join(ctx context.Context, in *JoinConfig, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaSetClient) RemoveNode(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaSetClient) Get(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaSetClient) Put(ctx context.Context, in *KVPair, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaSetClient) Delete(ctx context.Context, in *OneString, opts ...grpc.CallOption) (*OneString, error) {
	out := new(OneString)
	err := c.cc.Invoke(ctx, "/ReplicaSet/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaSetServer is the server API for ReplicaSet service.
// All implementations must embed UnimplementedReplicaSetServer
// for forward compatibility
type ReplicaSetServer interface {
	Init(context.Context, *InitConfig) (*OneString, error)
	Join(context.Context, *JoinConfig) (*OneString, error)
	RemoveNode(context.Context, *OneString) (*OneString, error)
	Get(context.Context, *OneString) (*OneString, error)
	Put(context.Context, *KVPair) (*OneString, error)
	Delete(context.Context, *OneString) (*OneString, error)
	mustEmbedUnimplementedReplicaSetServer()
}

// UnimplementedReplicaSetServer must be embedded to have forward compatible implementations.
type UnimplementedReplicaSetServer struct {
}

func (UnimplementedReplicaSetServer) Init(context.Context, *InitConfig) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedReplicaSetServer) Join(context.Context, *JoinConfig) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedReplicaSetServer) RemoveNode(context.Context, *OneString) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedReplicaSetServer) Get(context.Context, *OneString) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedReplicaSetServer) Put(context.Context, *KVPair) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedReplicaSetServer) Delete(context.Context, *OneString) (*OneString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedReplicaSetServer) mustEmbedUnimplementedReplicaSetServer() {}

// UnsafeReplicaSetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicaSetServer will
// result in compilation errors.
type UnsafeReplicaSetServer interface {
	mustEmbedUnimplementedReplicaSetServer()
}

func RegisterReplicaSetServer(s grpc.ServiceRegistrar, srv ReplicaSetServer) {
	s.RegisterService(&ReplicaSet_ServiceDesc, srv)
}

func _ReplicaSet_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).Init(ctx, req.(*InitConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaSet_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).Join(ctx, req.(*JoinConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaSet_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).RemoveNode(ctx, req.(*OneString))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaSet_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).Get(ctx, req.(*OneString))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaSet_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).Put(ctx, req.(*KVPair))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaSet_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaSetServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReplicaSet/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaSetServer).Delete(ctx, req.(*OneString))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicaSet_ServiceDesc is the grpc.ServiceDesc for ReplicaSet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicaSet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReplicaSet",
	HandlerType: (*ReplicaSetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _ReplicaSet_Init_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _ReplicaSet_Join_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _ReplicaSet_RemoveNode_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ReplicaSet_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _ReplicaSet_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ReplicaSet_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replica_set.proto",
}
